# -*- coding: utf-8 -*-
"""16.09.2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujnyUtFqf2UtkIvksZGWzu5bFYiaSPrM
"""

print('Python öğreniyorum')
print ('Eray Ünsal' , 'Taşkıran')
print(23432432)
print('HEelo dünya')

print("Eray")  # Ekrana Eray yazdırır

"""
Ad: Eray
Yaş: 25
Şehir: İstanbul
"""

sehir = 'İstanbul'
print(sehir)

puan = 50
print(puan)

puan = 75
print(puan)

sayi = 10
ondalikli_sayi = 1.2324
yazi = "Eray"
dogru_mu = True

print(type(sayi))
print(type(ondalikli_sayi))
print(type(yazi))
print(type(dogru_mu))

print(type(10))
print(type("10"))

a = 15
b = 4

print( a+b)
print(a-b)
print(a*b)
print(a/b)
print(17 % 5)
print(2 ** 8)

ad = input('Adınızı girin:')
print('merhaba', ad )

yas = int(input("Yaşınızı girin: "))
print("10 yıl sonraki yaşınız:", yas + 10)

a = 8
b = 12
print(a<b)
print(a>b)
print(a==b)

sayi = int (input('bir sayı gir '))
print(sayi==100)

yas = 22
ogrenci_mi = False

print(yas > 18 and ogrenci_mi)
print(yas > 18 or ogrenci_mi)
print(not ogrenci_mi)

yas = 22
kayitli_mi = True

print(yas > 18 and kayitli_mi)

sayi = int(input("Bir sayı girin: "))

if sayi > 0:
    print("Pozitif")
elif sayi < 0:
    print("Negatif")
else:
    print("Sayı sıfırdır.")

sınav = int(input('not gir :'))
if sınav >=50:
  print('geçti')
else:
  print('kaldı')

ad = "Eray"
soyad = "Ünsal"

tam_ad = ad + " " + soyad
print(tam_ad)

kelime = "Taşkıran"
print(len(kelime))

yazi = "Fenerbahçe"

print(yazi.upper())
print(yazi.lower())

sayi1 = int(input("Birinci sayıyı gir: "))
sayi2 = int(input("İkinci sayıyı gir: "))

carpim = sayi1 * sayi2

print("Çarpım:", carpim)

sayi = int(input("Bir sayı girin: "))

kare = sayi * sayi

print("Sayının karesi:", kare)



"""2. 11 soru"""

birim_fiyat = 1000
adet = 4
toplam_fiyat = birim_fiyat * adet
print('Toplam fiyat: ', toplam_fiyat)

maas = 8000
maas +=1500
print('yeni maaş: ', maas)

yas = int(input('Yaşınızı girin: '))
ogrenci = input( 'Öğrenci misin? evet - hayır --- ')

if yas > 65:
  print('Ücretsiz geçiş')
else:
  if ogrenci == 'evet':
    print('Öğrenci geçiş')

  else:
    print('Tam ücret')

sayi = int(input("Bir sayı girin: "))

if sayi > 0:
    if sayi % 2 == 0:
        print("Sayı hem pozitif hem de çifttir.")
    else:
        print("Sayı pozitif ama çift değildir.")
else:
    print("Sayı pozitif değildir.")

sicaklik = int(input("Sıcaklık değerini girin: "))

if sicaklik > 30:
    print("Sıcak")
elif sicaklik >= 15:
    print("Ilıman")
else:
    print("Soğuk")

ay = int(input("Ay numarasını girin: "))

if ay == 12 or ay == 1 or ay == 2:
    print("Kış")
elif ay == 3 or ay == 4 or ay == 5:
    print("İlkbahar")
elif ay == 6 or ay == 7 or ay == 8:
    print("Yaz")
elif ay == 9 or ay == 10 or ay == 11:
    print("Sonbahar")
else:
    print("Geçersiz")

sayilar = [5, 15, 8, 22, 3, 19]

en_buyuk = sayilar[0]

for sayi in sayilar:
    if sayi > en_buyuk:
        en_buyuk = sayi

print("En büyük sayı:", en_buyuk)

sayac = 0

for sayi in sayilar:
    if sayi > 10:
        sayac += 1

print("10'dan büyük sayı adedi:", sayac)

sayi = 10

while sayi >= 1:
    print(sayi)
    sayi -= 1

dogru_sifre = "1234"

sifre = input("Şifreyi girin: ")

while sifre != dogru_sifre:
    print("Şifre yanlış.")
    sifre = input("Şifreyi tekrar girin: ")

print("Şifre doğru.")

for sayi in range(1, 21):
    if sayi % 3 == 0:
        print(sayi)

        sayilar = [5, -3, 10, -8, 4, -1]

for sayi in sayilar:
    if sayi > 0:
        print("Pozitif:", sayi)
    elif sayi < 0:
        print("Negatif:", sayi)

def kup_al(sayi):
    return sayi ** 3

print(kup_al(4))

def topla(sayi1, sayi2):
    return sayi1 + sayi2

sonuc = topla(5, 10)

print(sonuc)

def sayi_durumu(sayi):
    if sayi > 0:
        return "Pozitif"
    elif sayi < 0:
        return "Negatif"
    else:
        return "Sıfır"

print(sayi_durumu(-5))

def en_buyuk_bul(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c

print(en_buyuk_bul(10, 25, 15))

sehirler = []

for i in range(5):
    sehir = input("Şehir adı girin: ")
    sehirler.append(sehir)

for i in range(len(sehirler)):
    print(i + 1, sehirler[i])

urunler = ["Telefon", "Bilgisayar", "Tablet", "Kulaklık"]

print(urunler)

silinecek_urun = input("Silmek istediğin ürünü gir: ")

if silinecek_urun in urunler:
    urunler.remove(silinecek_urun)
    print("Güncel liste:", urunler)
else:
    print("Ürün listede bulunamadı.")

ad = input("Adınızı girin: ")
soyad = input("Soyadınızı girin: ")
dogum_yili = int(input("Doğum yılınızı girin: "))

yas = 2026 - dogum_yili

print("Ad Soyad:", ad, soyad)
print("Yaş:", yas)

boy = float(input("Boyunuzu cm olarak girin: "))
kilo = float(input("Kilonuzu girin: "))

boy_metre = boy / 100

bmi = kilo / (boy_metre ** 2)

print("BMI:", bmi)

not1 = int(input("1. ders notu: "))
not2 = int(input("2. ders notu: "))
not3 = int(input("3. ders notu: "))
not4 = int(input("4. ders notu: "))

ortalama = (not1 + not2 + not3 + not4) / 4

print("Ortalama:", ortalama)

if ortalama >= 90:
    print("Harf notu: AA")
elif ortalama >= 85:
    print("Harf notu: BA")
elif ortalama >= 80:
    print("Harf notu: BB")
elif ortalama >= 75:
    print("Harf notu: CB")
elif ortalama >= 70:
    print("Harf notu: CC")
elif ortalama >= 65:
    print("Harf notu: DC")
elif ortalama >= 60:
    print("Harf notu: DD")
elif ortalama >= 50:
    print("Harf notu: FD")
else:
    print("Harf notu: FF")

    notlar = [not1, not2, not3, not4]

en_yuksek = notlar[0]
en_dusuk = notlar[0]

for notu in notlar:
    if notu > en_yuksek:
        en_yuksek = notu

    if notu < en_dusuk:
        en_dusuk = notu

print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk)

urunler = {
    "Kalem": 30,
    "Defter": 80,
    "Çanta": 450,
    "Kulaklık": 250
}

print("100 TL üzerindeki ürünler:")

for urun in urunler:
    if urunler[urun] > 100:
        print(urun, urunler[urun], "TL")

fiyatlar = [150, 200, 100, 120]

toplam = 0

for fiyat in fiyatlar:
    toplam += fiyat

print("Toplam tutar:", toplam, "TL")

if toplam > 500:
    print("%10 indirim kazandınız")

    indirim = toplam * 0.10
    yeni_toplam = toplam - indirim

    print("İndirimli tutar:", yeni_toplam, "TL")
else:
    print("İndirim kazanamadınız.")

"""sınıflar

"""

class Araba:
    def __init__(self, marka, model, hiz):
        self.marka = marka
        self.model = model
        self.hiz = hiz

    def hizlandir(self, artis):
        self.hiz += artis

    def bilgi_goster(self):
        print("Marka:", self.marka)
        print("Model:", self.model)
        print("Hız:", self.hiz, "km/s")


araba1 = Araba("Ford", "Puma", 200)

araba1.bilgi_goster()

araba1.hizlandir(55)

araba1.bilgi_goster()

class Dikdortgen:
    def __init__(self, uzunluk, genislik):
        self.uzunluk = uzunluk
        self.genislik = genislik

    def alan_hesapla(self):
        return self.uzunluk * self.genislik

    def cevre_hesapla(self):
        return 2 * (self.uzunluk + self.genislik)


dikdortgen1 = Dikdortgen(10, 5)

print("Alan:", dikdortgen1.alan_hesapla())
print("Çevre:", dikdortgen1.cevre_hesapla())

class Kitap:
    def __init__(self, ad, yazar, sayfa_sayisi):
        self.ad = ad
        self.yazar = yazar
        self.sayfa_sayisi = sayfa_sayisi

    def ozet(self):
        return self.ad + " - " + self.yazar + " (" + str(self.sayfa_sayisi) + " sayfa)"


kitap1 = Kitap("Klon", "Eray Ünsal", 2312)

print(kitap1.ozet())